language: node_js
node_js: '6.10.0'
cache: yarn
before_script:
  - git config --global user.name "Andy Chen"
  - git config --global user.email "shinningstar1001@gmail.com"
  - git clone --branch packages https://${GH_REF} ${PACKAGE_FOLDER}

script:
  - npm run build   
  - rsync -av --progress . /${PACKAGE_FOLDER} --exclude ${PACKAGE_FOLDER} 
  - cd ${PACKAGE_FOLDER}
  - sed -i -e 's/public\///' .gitignore
  - git add --all .
  - git commit --message "Update from travis ${TRAVIS_COMMIT_MESSAGE} [ci skip]"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" packages:packages

env:
  global:
    - GH_REF: github.com/Asing1001/Angular4-CRUD.git
    - PACKAGE_FOLDER: mypackages