language: node_js
node_js: '6.10.0'
cache: yarn
before_script:
  - git config --global user.name "Andy Chen"
  - git config --global user.email "shinningstar1001@gmail.com"
script:
  - npm run build   
  - sed -i -e 's/public\///' .gitignore
  - git add --all .
  - git commit --message "Automatically update from travis-ci [ci skip]"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:packages

env:
  global:
    - GH_REF: github.com/Asing1001/Angular4-CRUD.git